what the heck

diff --git a/bin/test-core-gems b/bin/test-core-gems
--- a/bin/test-core-gems
+++ b/bin/test-core-gems
@@ -28,11 +28,13 @@ for ((i = 0; i < ${#packages[@]}; i++)); do
   echo "#####################################################################"
   echo ""
   echo "Running tests for ${packages[$i]}"
+  echo "FAILED_TESTS = ${FAILED_TESTS[@]}"
   echo ""
   echo "#####################################################################"
   bundle exec rails test local/bullet_train-core/${packages[$i]}
 
   if [ $? == "1" ]; then
+    echo "we failed with an exit code of $? in ${packages[$i]}"
     FAILED_TESTS+=("${packages[$i]}")
   fi
 
