wat

diff --git a/bin/test-core-gems b/bin/test-core-gems
--- a/bin/test-core-gems
+++ b/bin/test-core-gems
@@ -33,8 +33,9 @@ for ((i = 0; i < ${#packages[@]}; i++)); do
   echo "#####################################################################"
   bundle exec rails test local/bullet_train-core/${packages[$i]}
 
-  if [ $? == "1" ]; then
-    echo "we failed with an exit code of $? in ${packages[$i]}"
+  EXIT_CODE=$?
+  if [ $EXIT_CODE == "1" ]; then
+    echo "we failed with an exit code of $EXIT_CODE in ${packages[$i]}"
     FAILED_TESTS+=("${packages[$i]}")
   fi
 
